name: 'Setup Node and deps'
description: ''
inputs:
  node-version:
    description: 'Node version'
    required: true
  working-directory:
    description: 'workdir'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Node.js ${{ inputs.node-version }}"
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - name: "Install dependencies"
      run: "npm ci"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
