events {}
http {
    proxy_cache_path /cache keys_zone=mycache:10m;

    upstream myapp {
        server backend1:3000;
        server backend2:3000;
        server backend3:3000;
    }

    server {
        listen 80;

        location / {
            root /statics;
        }

        location /api/ {
            proxy_pass http://myapp/;
        }

        location /api/stats {
            proxy_pass http://myapp/stats;
            add_header X-Cache-Status $upstream_cache_status always;
            proxy_cache mycache;
            proxy_cache_valid any 30s;
        }       
    }
}